### ISSUE TITLE
bazel-toolchains broken in bazel CI at HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel-toolchains#125]
Looks like 0e40c7893e16a64c48084920e3a6b7a9dda72522 broke buildkite continuous integration both in this project and bazel project (in bazel's 'downstream dependencies' tracker)

**Comment by xingao267** [comment]
CI is green now. Fixed by https://github.com/bazelbuild/bazel-toolchains/commit/7f0f38d6b45173fc33d74a4b454bc910d3d1c65f. This was due to accessing image in gcr.io/cloud-marketplace now requires auth. We've switched to use l.gcr.io which is a alias that doesn't require auth for now to fetch testing images. Pending @buchgr to configure gcloud auth for fetching images in Buildkite machines. Will switch back to the auth mirror afterwards. Thanks!
