### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dionescu** [bazelbuild/bazel-toolchains#171]
I get the errors below when I try the toolchain. I'm on Ubuntu 16.04 using bazel 16.01.

Also, is there an overview of the toolchains? Do they only apply for remote execution? Do they always run inside Docker? Can I use it on my local machine?

`bazel run --config=remote --config=remote-xxsan --config=remote-asan :use_after_free 

Starting local Bazel server and connecting to it...
WARNING: option '--host_javabase' was expanded to from both option '--config=remote' (source command line options) and option '--config=remote' (source command line options)
WARNING: option '--javabase' was expanded to from both option '--config=remote' (source command line options) and option '--config=remote' (source command line options)
WARNING: option '--crosstool_top' was expanded to from both option '--config=remote' (source command line options) and option '--config=remote' (source command line options)
WARNING: option '--host_platform_remote_properties_override' was expanded to from both option '--config=remote' (source command line options) and option '--config=remote' (source command line options)
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:99:1: name 'cc_toolchain_type' is not defined (did you mean 'toolchain_type'?)
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:54:1: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:compiler_deps' contains an error and its package is in error and referenced by '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8'
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:54:1: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:compiler_deps' contains an error and its package is in error and referenced by '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8'
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:54:1: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:empty' contains an error and its package is in error and referenced by '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8'
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:54:1: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:empty' contains an error and its package is in error and referenced by '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8'
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:54:1: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:compiler_deps' contains an error and its package is in error and referenced by '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8'
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:54:1: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:empty' contains an error and its package is in error and referenced by '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8'
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:54:1: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:empty' contains an error and its package is in error and referenced by '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8'
ERROR: /home/dragos/.cache/bazel/_bazel_dragos/0308431f44215f5d9974112361ef87b9/external/bazel_toolchains/configs/debian8_clang/0.3.0/bazel_0.10.0/BUILD:54:1: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:empty' contains an error and its package is in error and referenced by '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8'
ERROR: /home/dragos/bazel/examples/asan/BUILD:1:1: every rule of type cc_binary implicitly depends upon the target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8', but this target could not be found because of: Target '@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.10.0:cc-compiler-k8' contains an error and its package is in error`

**Comment by xingao267** [comment]
Hi @dionescu, thanks for reporting.

https://github.com/bazelbuild/bazel-toolchains/blob/master/README.md has a little overview of the toolchains, but we can definitely do better.

These toolchains are used mostly for our remote execution, but not necessarily. These toolchains specify the configuration (tool/compiler locations etc, e.g. https://github.com/bazelbuild/bazel-toolchains/blob/master/configs/ubuntu16_04_clang/1.0/bazel_0.16.1/default/CROSSTOOL#L155) of the execution environment that Bazel will run compiler commands in. You can use these configs together with the corresponding container in the Bazel's docker sandbox mode (https://docs.bazel.build/versions/master/remote-execution-sandbox.html). For example, configs under https://github.com/bazelbuild/bazel-toolchains/tree/master/configs/ubuntu16_04_clang/1.0 corresponding to container https://launcher.gcr.io/google/rbe-ubuntu16-04 while configs under https://github.com/bazelbuild/bazel-toolchains/tree/master/configs/debian8_clang/0.3.0 correspond to container https://launcher.gcr.io/google/rbe-debian8

For local mode, you don't need to use these configs because Bazel will examine your local environment and "auto-configure" itself to use your local machine's compilers.

What would you like to achieve with your Bazel command? Do you want to start a remote build, a sanitizer build or both?

The bazel command you run failed due to few reasons:

1. you didn't not supply the .bazelrc file (https://github.com/bazelbuild/bazel-toolchains/blob/master/configs/ubuntu16_04_clang/1.0/toolchain.bazelrc) which defines the --config=remote, --config=remote-xxan and --config=asan. For how to use bazelrc files, please take a look at https://docs.bazel.build/versions/master/user-manual.html#bazelrc.

2. to use our remote build service, you would need to apply for an instance first. We can discuss more about and follow the official process if you are interested.

3. if you want to launch a sanitizer build, you need a proper environment and compiler to support it as well. These toolchains are just flags to tell bazel how to configure the compiler. If your environment and compiler does not support it, then it won't run. Does you environment that starts the Bazel build have clang that supports sanitizer installed?

Just FYI, we are launching a Ubuntu1604-based Bazel container with clang installed https://console.cloud.google.com/marketplace/details/google/bazel. Version 0.16.1 will soon come out, which will support sanitizer build. Stay tuned. That should make life much easier for people who want to try out Bazel and sanitizer builds.

**Comment by nlopezgi** [comment]
Hi @dionescu (adding on to Xin's response)
Can you let us know what your use case is and why do you want to use the toolchains in this repo? We can move from there to see how what we have here is of use to you.

**Comment by dionescu** [comment]
Thank you for the overview, Xin!

Regarding the bazelrc file, I did have the one you mentioned in my local tools folder. I probably misunderstood how the toolchain you provided can be used. I expected I could also run it locally within a Docker container.

My specific interest was in a toolchain that supports sanitizers (especially MSAN instrumented libcxx) out fo the box. None of the toolchains out there seem to do this properly and I'd rather not maintain my own.

At the moment, I'm only playing around with some pet projects (e.g. building and experimenting with Abseil) so don't need to full power of a remote build system in the cloud.

**Comment by xingao267** [comment]
It's great to know you have this use case, and it's one that our Bazel container just supports. Our latest Bazel/Clang container is just published at https://console.cloud.google.com/marketplace/details/google/bazel, checkout the version 0.16.1, and the starting guide shows how you can do a sanitizer build with abseil-cpp project.

**Comment by xingao267** [comment]
I'm closing this issue. Feel free to try out the bazel container @dionescu and report back any issues related to that. Thanks!!
