### ISSUE TITLE
Disallow using CROSSTOOL to select the cc_toolchain label

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel-toolchains#216]
Hello :)

I'm back again, I promise this is the last time. Today the incompatible flag for https://github.com/bazelbuild/bazel/issues/6382 has been flipped, and it affects the bazel toolchains (https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/539#9c3cb2d3-791d-4e1f-944d-f768fb2810be). Please see migration docs here: https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disallow-using-crosstool-to-select-the-cc_toolchain-label, and let me know if you have problems.

Extra points for also updating bazel-toolchains versions in rules_go, rules_rust, rules_kotlin, and rules_scala, but I can also do that.

Please create an issue at https://github.com/bazelbuild/continuous-integration to reenable bazel-toolchains on the downstream pipeline.

**Comment by xingao267** [comment]
Working on this.

**Comment by mhlopko** [comment]
You're amazing Xin! Thank you!

**Comment by xingao267** [comment]
Ok. This is a little more complicated than I initially thought. The reason why it is failing is because the buildkite CI is using old toolchain configs (0.16.1), and those are not compatible with bazel head. So the fix would be I'll first update all bazel rule repos' WORKSPACE pin of bazel_toolchains to our latest, which will include our latest toolchain configs for Bazel 0.18.0. Then I'll update the toolchain flags in Buildkite CI.

**Comment by mhlopko** [comment]
And by all rules you mean rules_go, rules_rust, rules_kotlin, and rules_scala, right? Because others were not failing?

**Comment by xingao267** [comment]
Yes. All the rules that enabled rbe_ubuntu1604 platform in their buildkite ci.

**Comment by xingao267** [comment]
I'm creating a PR in bazel-toolchains repo first to add a latest alias to crosstool and toolchain targets, so we don't need to modify buildkite configs in the future again.

**Comment by mhlopko** [comment]
Can this be closed now?

**Comment by nlopezgi** [comment]
afaik yes, please reopen if there are any issues related to this still pending.
