### ISSUE TITLE
Syntax Error: 'async' is a reserved word in Python >= 3.7

### ISSUE THREAD

**Issue by cclauss** [bazelbuild/bazel-toolchains#252]
[flake8](http://flake8.pycqa.org) testing of https://github.com/bazelbuild/bazel-toolchains on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./container/build.py:407:61: E999 SyntaxError: invalid syntax
                          arguments.bucket or arguments.async):
                                                            ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by nlopezgi** [comment]
bazel-toolchains depends on rules_docker (https://github.com/bazelbuild/rules_docker/), and rules_docker depends on containerregistry (https://github.com/google/containerregistry). Unfortunately containerregistry is not compatible with py3. You need to run your builds using a py2 top. You can do this by either setting your path variable for python to point to py2, or by explicitly passing a --python_top flag https://docs.bazel.build/versions/master/command-line-reference.html)  pointing to a py2 py_runtime rule (e.g., https://github.com/bazelbuild/rules_docker/blob/master/python/BUILD#L25) or passing a --python_path flag and passing there the absolute path to a py2 binary. 
Note if your build actually depends on using py3 for other targets, it will not be possible to run in the same build command those targets and the ones you are trying to execute from this repo. For a long term fix for this issue please see https://github.com/bazelbuild/rules_docker/issues/580.

Please let me know a bit more about your use case so I can help you find a viable solution if the py_xx flags will not cut it for you. Closing, but let me know to reopen if you need more advice.

**Comment by nlopezgi** [comment]
Apologies, just noticed your error is not related to containerregistry (which was my initial thought as its the source of most of my issues related to python). 
We will soon be deprecating build.py as a means to drive building our containers, so we;'re not actively making improvements to this script. 

To get around this issue you can try to run directly the specific targets to build a container (instead of using the build.py script). For instance, this target (https://github.com/nlopezgi/bazel-toolchains/blob/master/container/ubuntu16_04/builders/rbe-ubuntu16_04/BUILD#L49) can be used to build rbe-ubuntu16_04) and this target (https://github.com/nlopezgi/bazel-toolchains/blob/master/container/ubuntu16_04/builders/bazel/BUILD) can be used to build the bazel container. 
Note that build.py just calls those targets and does a couple of additional things (uploading the container to gcr and uploading a tar file to gcs), so for most use cases, building the container directly using the Bazel targets should suffice. Note however, that when running these targets you might run into other issues related to py2/py3 compatibility with the container_image targets that are executed by the toolchain rules, due to containerregistry not being compatible with py3.

If you are really set on using build.py, it should be feasible to get it to be compatible with py3. I'll be happy to review any PRs you send for that purpose.

Could you also please elaborate a bit more about your use case (i.e., why do you want to build these containers?)
