### ISSUE TITLE
rbe_autoconfig allow extra remote_execution_properties

### ISSUE THREAD

**Issue by ebracho** [bazelbuild/bazel-toolchains#356]
For our rbe platform we need to configure more than just the container-image (e.g. `dockerNetwork`, `dockerAddCapabilities`, `dockerSiblingContainers`). Right now we have to edit them in after generating the autoconfig. It would be great if we could pass them through the `rbe_autoconfig` rule itself.

**Comment by nlopezgi** [comment]
thanks for opening this issue. we are planning on spring this on the future, for now, the recommended solution is to declare a platform that had as parent the generated platform and which adds the additional properties. example: https://github.com/bazelbuild/rules_docker/blob/master/toolchains/BUILD

**Comment by ebracho** [comment]
That should work perfectly, thanks!

**Comment by buchgr** [comment]
I'd also like to have this!

**Comment by eytankidron** [comment]
As of bazel 1.0 there is a now a way to do this.

Both platforms and rbe_autoconfig now have a field named exec_properties.

In a platform, exec_properties is replacing the deprecated remote_execution_properties. Unlike remote_execution_properties, exec_properties receives a string->string dict and not a protobuf-serialized-as-string.

rbe_autoconfig now also has a new field named use_legacy_platform_definition. For backwards compatibility it is set by default to True, but if you want the underlying platform to use the exec_properties field, rather than remote_execution_properties, you should set it to False. If you want to populate exec_properties directly in rbe_autoconfig, you must set use_legacy_platform_definition to False.

exec_properties receives a string->string dict but do not populate this dict manually. Instead, please use create_exec_properties_dict (see https://github.com/bazelbuild/bazel-toolchains/tree/master/rules/exec_properties). This is a bazel macro that creates this dict for you and makes the proper type checks (and some basic value checks) to ensure that RBE can consume these remote execution properties.

In a related note, as of bazel 1.0 individual targets now also have an exec_properties attribute, which are added to (or override) the exec_properties of the platform for the execution of that particular target. For more on this see https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes. This may remove the need for creating inheriting platforms in many cases. 

The properties that you mentioned (dockerNetwork, dockerAddCapabilities, dockerSiblingContainers) may be set in rbe_autoconfig if you want them for all targets, or you may configure them per target if they are needed only for very specific tests. No need to use toolchain constraints for this to work.
