### ISSUE TITLE
Unable to execute pkg_rpm remotely

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel-toolchains#456]
Due to `rpmbuild` executable not being present in Ubuntu image used in RBE, we at @GraknLabs are unable to build [`pkg_rpm`](https://docs.bazel.build/versions/master/be/pkg.html#pkg_rpm) targets remotely. Inclusion of [`rpm`](https://packages.ubuntu.com/trusty/rpm) package which contains `rpmbuild` executable will be much appreciated.

I decided to post issue in this repo since this repo was linked to [here](https://console.cloud.google.com/marketplace/details/google/rbe-debian8):
>Source code and instructions for reproducing this docker image.

**Comment by nlopezgi** [comment]
hi @vmax 
we try to keep the rbe ubuntu iamge slim by design and only include in it the set of tools required for some Bazel builds. If you need the rpmbuild executable in some actions, you will need to create a custom container (ideally extending from the rbe ubuntu one) and then use that for your RBE builds. Instructions for how to use a custom container are in the RBE docs. Alternatively please contact rbe support channels directly (and I or someone else from RBE team) can respond there to point you to documentation about creating and using a custom container which extends from the rbe ubuntu image in RBE builds. 
Thanks!

**Comment by haikalpribadi** [comment]
hi @nlopezgi, your suggestion makes sense. However, we worry that we won't get up to date with the latest RBE image at all times.

**Comment by nlopezgi** [comment]
hi @haikalpribadi ,
Keeping a container up to date is a legitimate concern. We publish updated versions of the rbe containers including updates to all tools ~weekly. You would need to rebuild your container based on ours also ~weekly in order to get all these updates. In practice, though, we have seen many users don't regularly rebuild their containers and we have not had this be a problem so far. As I mentioned on the comment above, its better to reach out through RBE support channels if this is a concern for you so we can try to resolve better there.
fyi @martensryan
