### ISSUE TITLE
Please move from native to Skylark rules for external git/http repositories

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel-toolchains#66]
Bazel is planning to move away from native rules for external repositories to
Skylark rules, mainly because bundling every version control system in bazel
does not scale. As part of this effort, we plan to submit
https://bazel-review.googlesource.com/c/bazel/+/55932 soon, which will cause
bazel by default to insist that the skylark versions the git and http rules for
external repositories be used. This can be disabled by a flag for at least the
next 6 months, but we still would appreciate if you could adopt your repository
to use the Skylark versions of those rules soon.

A test run of downstream projects with that flag flip in bazel enabled can
be found at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/286

For more background, see
- the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository

Thanks.

**Comment by xingao267** [comment]
We should be able to proceed with this as https://github.com/bazelbuild/bazel/issues/5633 is fixed.

**Comment by mhlopko** [comment]
Howdy all,
it looks to me that bazelbuild/bazel#5633 is fixed, and you can fix your project. In the meantime the incompatible flag was flipped in Bazel, and bazel-toolchains are red on our downstream pipeline: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/531#e1dee82d-4f9f-4c89-98b1-781c0f58de38. I'll disable bazel-toolchains for the meantime, please create issue at https://github.com/bazelbuild/continuous-integration to reenable bazel-toolchains once this issue is fixed. Thank you!

**Comment by mhlopko** [comment]
rules_kotlin are also affected by bazel-toolchains, would you mind updating their WORKSPACE to use a fixed version of bazel-toolchains once this is fixed?

**Comment by xingao267** [comment]
Thanks. Working on fixing this.

**Comment by xingao267** [comment]
Should be fixed. Please reopen if there is any more issue related to this.

I'm also sending a PR to continuous-integration to re-enable ci for bazel-toolchains.
